# Generated by Django 4.1.1 on 2022-11-14 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UKpracaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='experience',
            new_name='userName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='userSurname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
    ]
